base-image: ghcr.io/ublue-os/bazzite
image-version: stable

name: debrid-livingroom-os
description: SteamOS console with on-demand Real-Debrid game installing, Stremio, and Norwegian IPTV.

modules:
  - type: rpm-ostree
    install:
      - rclone
      - docker
      - docker-compose
      - zenity

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.github.linuxmint.hypnotix
          - com.stremio.Stremio

  - type: files
    files:
      - source: system_files
        destination: /

  - type: systemd
    system:
      enabled:
        - docker.service
        - debrid-first-boot-dirs.service
    user:
      enabled:
        - rclone-mount-debrid.service

  - type: script
    scripts:
      - |
        #!/usr/bin/env bash
        chmod +x /usr/bin/debrid-first-boot-dirs.sh
        chmod +x /usr/bin/debrid-first-run-setup.sh
